### ISSUE TITLE
Create users

### ISSUE THREAD

**Issue by bobcomp11** [UK-AS-HIVE/Scriptorium#1]
Upon installing this application how do I let users register to test the software?

**Comment by mpaddock** [comment]
Ok - 446b2fa253863feb9a8ce67da34eff69e3aa4457 improves this significantly. The account approval process was requested for our hosted version of Scriptorium, but we didn't do a great job with the option to turn it off. The setting in `settings.json.example` for accountApproval should now let users create accounts with a password as expected if it's set to `false`. You can start meteor with `meteor --settings settings.json` (or `settings.json.example` if you just want to use the version already in the repo) and that should take care of it.
